### ISSUE TITLE
Differences with skeleton

### ISSUE THREAD

**Issue by coretl** [DiamondLightSource/python-copier-template#1]
These are the things I spotted that are different to skeleton:
- `project_name` should be `package_name`, with help "The import name of the python package", and should be [checked that it is a valid python identifier](https://github.com/DiamondLightSource/python3-pip-skeleton-cli/blob/2e0ad72e12b6a30da0505f022113d86ee784a4cc/src/python3_pip_skeleton/__main__.py#L200-L204)
- `user_name` should be `github_org`, and only asked for if `git_platform == "GitHub", with help "The GitHub organisation that will contain this repo. Set to your GitHub username to make a personal repo, or `DiamondLightSource` if you have permissions to make it in the DiamondLightSource organisation.". 
- The repo name (contained in the URL for the README) is not the same as `project_name`, but is actually the name of the directory that we ran copier copy on. I think the full path is available as `_copier_conf.dst_path` so maybe `_copier_conf.dst_path.name` can be set as `repo_name`?
- Why do we prompt for `url`? Do we actually use it anywhere?
- Can we get name and email from auth?
- `settings.json` should use `--cov={{package_name}}`
- `tests/test_cli.py` should still be present

**Comment by M-Chan** [comment]
`_copier_conf.dst_path` is annoying as it doesn't take the folder name but rather the expression used to define location (I cd ino the directory and ran copier with '.' as the place to run and copier took `_copier_conf.dst_path = .`
`_copier_conf.dst_path.name` gives nothing
also I only tested this as an after message as trying to set the `repo_name` from this gives `_copier_conf.dst_path` is not defined

**Comment by coretl** [comment]
How about `_copier_conf.dst_path.resolve().name`? That should turn it into an absolute path before taking the name

**Comment by coretl** [comment]
From https://copier.readthedocs.io/en/stable/configuring/#advanced-prompt-formatting

> when: Condition that, if false, skips the question.
> If it is a boolean, it is used directly. Setting it to false is useful for creating a computed value.
> If a question is skipped, its answer is not recorded, but its default value is available in the render context.

So if you take `url` and set `when: false` and `default: https://github.com/{{ org }}/{{ repo_name }}` then it would become a calculated field

**Comment by M-Chan** [comment]
Thanks Tom but I've already done that
I'm on branch 'fixing_differences'

**Comment by coretl** [comment]
As for dst_path, this is not supported at the moment, so we will have to ask for `repo_name`: https://github.com/copier-org/copier/issues/1050
