### ISSUE TITLE
Move ADRs out of template

### ISSUE THREAD

**Issue by callumforrester** [DiamondLightSource/python-copier-template#136]
Adopting the template, which contains 2 ADRs, is likely to cause numbering conflicts in projects with existing ADRs. A proposal discussed among @DiamondJoseph @joeshannon @gilesknap and @callumforrester is to move all ADRs out of the template into the top level of this repo, leaving the template blank.

@coretl any thoughts?

**Comment by DiamondJoseph** [comment]
I think that the 2 existing ADRs are valid decisions to assume that someone adopting the copier has made, and bootstrap the concept of ADRs. But any future ADRs that are decisions made for Copier are likely not decisions made by the host repository, and shouldn't be propagated.

**Comment by coretl** [comment]
> I think that the 2 existing ADRs are valid decisions to assume that someone adopting the copier has made, and bootstrap the concept of ADRs. But any future ADRs that are decisions made for Copier are likely not decisions made by the host repository, and shouldn't be propagated.

What he said.

These: https://github.com/DiamondLightSource/python-copier-template/tree/main/docs/explanations/decisions will grow as we make decisions that are related to python-copier-template, but they don't make it into expanded templates.

These: https://github.com/DiamondLightSource/python-copier-template/tree/main/template/%7B%25%20if%20sphinx%20%25%7Ddocs%7B%25%20endif%20%25%7D/explanations/decisions should be static and there will only ever be 2 of them.

I suggest we keep it like it is, but renumber the conflicting ones if we ever adopt into something which already has ADRs

**Comment by callumforrester** [comment]
It is very easy to forget, is all, we would have in https://github.com/DiamondLightSource/blueapi/pull/384 if not for @DiamondJoseph
