### ISSUE TITLE
Ruff errors in `.github/pages/make_switcher.py`

### ISSUE THREAD

**Issue by GDYendell** [DiamondLightSource/python-copier-template#139]
I have just adopted the template into FastCS and on running tox, ruff produced errors:

```
lint with ruff...........................................................Failed
- hook id: ruff
- exit code: 1

.github/pages/make_switcher.py:6:1: UP035 `typing.List` is deprecated, use `list` instead
.github/pages/make_switcher.py:9:49: UP006 [*] Use `list` instead of `List` for type annotation
.github/pages/make_switcher.py:15:38: UP006 [*] Use `list` instead of `List` for type annotation
.github/pages/make_switcher.py:21:31: UP006 [*] Use `list` instead of `List` for type annotation
.github/pages/make_switcher.py:27:33: UP007 [*] Use `X | Y` for type annotations
.github/pages/make_switcher.py:27:51: UP006 [*] Use `list` instead of `List` for type annotation
.github/pages/make_switcher.py:44:15: UP006 [*] Use `list` instead of `List` for type annotation
```

but neither the template project itself or the example seem to have the same problem. And `ruff --fix` and `ruff format` on the file don't change anything.

I am pretty sure these are issues that should be fixed and I can make a PR for it, but I am confused what the difference is here.

**Comment by coretl** [comment]
The `UP` errors are for old python syntax that has a better modern equivalent. It uses the minimum python from pyproject.toml to work this out. You can also set the minimum python separately in `[tool.ruff]` to silence these until copier ditches older pythons following the numpy python deprecation scheme...

**Comment by coretl** [comment]
https://docs.astral.sh/ruff/settings/#target-version

**Comment by GDYendell** [comment]
Ahh OK, I did change the minimum version.
