### ISSUE TITLE
Correctly template `spec.type` and `spec.lifecycle` in `copier-template.yaml`

### ISSUE THREAD

**Issue by garryod** [DiamondLightSource/python-copier-template#181]
There are currently [32 components](https://dev-portal.diamond.ac.uk/catalog?filters%5Bkind%5D=component&filters%5Btype%5D=documentation&filters%5Blifecycles%5D=experimental&filters%5Buser%5D=all) erroneously marked with `spec.type=documentation` and `spec.lifecycle=experimental` in the developer portal, the vast majority of which originated from this template. Please could you update the template such that these fields must be specified. Additionally, it would be good to remove `sscc` as the default for `owner` as it has been used in 22 of the 32 aforementioned repos

**Comment by callumforrester** [comment]
Looking at this now...

I agree that `spec.type=documentation` is erroneous, but I'm inclined to say that `spec.lifecycle=experimental` is a reasonable default value for new projects. Of the list you linked, I would consider almost all of the components that come from this template to be experimental, some may be arguably alpha. I may have misunderstood the classification though, open to other views.

**Comment by GDYendell** [comment]
I agree most projects will start as experimental, but if it is a copier question then people will (might) read it when they update to the latest version and consider changing it.
