### ISSUE TITLE
Match FROM and as casing in Dockerfiles

### ISSUE THREAD

**Issue by DominicOram** [DiamondLightSource/python-copier-template#188]
When using the template I currently get warnings that the `FROM` and `as` used in the `Docker` files are not consistent https://github.com/DiamondLightSource/mx_bluesky/pull/159/files#diff-dd2c0eb6ea5cfc6c4bd4eac30934e2d5746747af48fef6da689e85b752f39557. I agree with the warnings that these look messy.

## Acceptance Criteria
* `FROM` and `as` match case whenever they are used in Dockerfiles made by the template

**Comment by vredchenko** [comment]
I just attempted to fix this however it seems already fixed? @DominicOram please confirm if it's ok to close this issue or am I missing something?

![Screenshot from 2024-10-21 16-43-48](https://github.com/user-attachments/assets/28e8458c-1f70-4f0e-803c-4aa2a4746677)

**Comment by DominicOram** [comment]
Yh,looks like @coretl just fixed it https://github.com/DiamondLightSource/python-copier-template/commit/6e7f62c01b447e0475472e3aa3d4014361d4ecde. Happy to close this
