### ISSUE TITLE
Bash autocomplete for `git` and `tox` in devcontainer

### ISSUE THREAD

**Issue by callumforrester** [DiamondLightSource/python-copier-template#219]
Following on from https://github.com/DiamondLightSource/python3-pip-skeleton/issues/126 in the old pip skeleton. It would be very nice to have git extended autocompletion in the devcontainer, the tox autocompletion would also be nice.

**Comment by coretl** [comment]
Since #216 you get git autocompletion, not sure it's worth doing tox as we are likely to be using `uv` at some point in the medium term

**Comment by callumforrester** [comment]
Agreed, closing, thanks
